export default [
  {
    id: 1,
    img: "card_content_image_1.png",
    title: "Life lessons with Katie Zaferes",
    rating: 5.0,
    rating_num: 6,
    location: "USA",
    price: 136,
    slots: 0,
  },
  {
    id: 2,
    img: "card_content_image_2.png",
    title: "Learn wedding photography",
    rating: 5.0,
    rating_num: 30,
    location: "Online",
    price: 125,
    slots: 1,
  },
  {
    id: 3,
    img: "card_content_image_3.png",
    title: "Creative Cooking",
    rating: 4.7,
    rating_num: 26,
    location: "England",
    price: 140,
    slots: 0,
  },
  {
    id: 4,
    img: "card_content_image_4.png",
    title: "Mastering Meditation",
    rating: 4.5,
    rating_num: 12,
    location: "India",
    price: 175,
    slots: 1,
  },
  {
    id: 5,
    img: "card_content_image_5.png",
    title: "Gardening Guidance",
    rating: 4.3,
    rating_num: 23,
    location: "Online",
    price: 100,
    slots: 0,
  },
  {
    id: 6,
    img: "card_content_image_5.png",
    title: "Gardening Guidance",
    rating: 4.3,
    rating_num: 23,
    location: "Russia",
    price: 100,
    slots: 0,
  },
  {
    id: 7,
    img: "card_content_image_5.png",
    title: "Gardening Guidance",
    rating: 4.3,
    rating_num: 23,
    location: "Online",
    price: 100,
    slots: 0,
  },
  {
    id: 8,
    img: "card_content_image_5.png",
    title: "Gardening Guidance",
    rating: 4.3,
    rating_num: 23,
    location: "Online",
    price: 100,
    slots: 0,
  },
];
